### ISSUE TITLE
Fatal: Could not open database: open /bsc/node/geth/chaindata/ancient/chain/headers.cidx: no such file or directory

### ISSUE THREAD

**Issue by vaibhavraj05** [bnb-chain/bsc-snapshots#305]
i am trying to setup bsc node on my system with docker but i am facing issue 

1. first i downloaded the data from below website and with the given link 
`https://github.com/48Club/bsc-snapshots/tree/main#bsc-snapshots`
`https://snapshots.48.club/geth.fast.33660414.tar.zst`

I run the command 

```shell 
wget https://snapshots.48.club/geth.fast.33660414.tar.zst -O - | zstd -cd | tar xf -
```

and its download the `geth.fast/geth/chainnode` and `chaindata` contain all data 

2. Then i downloaded mainnet using below command provided on bsc website
```shell
wget   $(curl -s https://api.github.com/repos/bnb-chain/bsc/releases/latest |grep browser_ |grep mainnet |cut -d\" -f4)
unzip mainnet.zip
```
> And my folder structure look like this 
<img width="319" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/117675608/84c3951b-3043-4e9f-ab0e-fcd87c6453ee">

3. below is my docker compose

```yaml
version: "3.3"
services: 
  bsc:
    image : ghcr.io/bnb-chain/bsc:latest
    container_name: bsc
    restart: always
    ports:
      - 8575:8575
    volumes:
      - /bsc/config:/bsc/config
      - /bsc/data/geth.fast:/bsc/node
    command: --http.addr 0.0.0.0 --http.port 8575 --http.vhosts '*' --verbosity 5
```

these are the logs for the docker compose 
<img width="1300" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/117675608/7b3d5072-6821-4564-8e2d-4133839b8438">

and while running this command in container 
`geth --datadir node init ./config/genesis.json `
getting below error 
<img width="937" alt="image" src="https://github.com/bnb-chain/bsc-snapshots/assets/117675608/328de90d-369d-4569-aab7-d4ee7acee1f7">

**Fatal: Could not open database: open /bsc/node/geth/chaindata/ancient/chain/headers.cidx: no such file or directory**
